version: '3.1'

services:

#  proposta:
#    image: marcoscoutozup/proposta:latest
#    ports:
#      - 8080:8080
#    networks:
#      - backend
#    depends_on:
#      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: proposta
    ports:
      - 5434:5432
#    networks:
#      - backend

  adminer:
    image: adminer
    ports:
      - 9000:8080

#networks:
#  backend: