spring:
  profiles:
    active: test
  autoconfigure:
    exclude: org.keycloak.adapters.springboot.KeycloakAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ''
          jtw-set-uri: ''
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: false
  jpa:
    properties:
      hibernate:
        show_sql: false

cron:
  habilitada: false
